{"name": "test_vwo_login_positive", "status": "broken", "statusDetails": {"message": "TypeError: LoginPage.login_to_vmo() got an unexpected keyword argument 'user'", "trace": "self = <tests.vmoLoginTests.pom.test_login.TestLogin object at 0x10262bed0>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"93a0a5588b0a8d7d189c8566cf888050\")>\n\n    @allure.epic(\"VWO Login Test\")\n    @allure.feature(\"TC#1 - VWO App Positive Test\")\n    @pytest.mark.usefixtures(\"setup\")\n    def test_vwo_login_positive(self, setup):\n        driver = setup\n        driver.get(self.base_url)\n        loginPage = LoginPage(driver)\n>       loginPage.login_to_vmo(user=self.username, pwd=self.password)\nE       TypeError: LoginPage.login_to_vmo() got an unexpected keyword argument 'user'\n\ntest_login.py:34: TypeError"}, "start": 1708229487493, "stop": 1708229495077, "uuid": "3b6453c2-0dda-414f-aca8-ebbbd7179e59", "historyId": "063967906f3f3e8bd67115b608b7b12e", "testCaseId": "063967906f3f3e8bd67115b608b7b12e", "fullName": "tests.vmoLoginTests.pom.test_login.TestLogin#test_vwo_login_positive", "labels": [{"name": "feature", "value": "TC#1 - VWO App Positive Test"}, {"name": "epic", "value": "VWO Login Test"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests.vmoLoginTests.pom"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "GaneshGrandhi.local"}, {"name": "thread", "value": "13227-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vmoLoginTests.pom.test_login"}]}