{"uuid": "6b96187d-b4be-4492-9efe-997a994db0c2", "children": ["224a159e-d55a-4f26-baac-819f791ca2bb"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "ValueError: setup did not yield a value\n", "trace": "  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/_pytest/fixtures.py\", line 912, in call_fixture_func\n    raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n"}, "start": 1708228849119, "stop": 1708228850952}], "start": 1708228849119, "stop": 1708228851065}