{"uuid": "5962b01b-d316-438c-9f98-08cf44126222", "children": ["d514660b-6e25-4ab2-a71c-42a267a53ec4"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "ValueError: setup did not yield a value\n", "trace": "  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Ganesh/PyWebAutomation/venv_provided/lib/python3.11/site-packages/_pytest/fixtures.py\", line 912, in call_fixture_func\n    raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n"}, "start": 1708228876541, "stop": 1708228877752}], "start": 1708228876541, "stop": 1708228877866}